# Use root/example as user/password credentials
version: '3.6'
services:
  postgres:
    image: postgres:13
    shm_size: 1g
    container_name: sendy-postgres-dev
    restart: always
    networks:
      - sendy-dev-network
    volumes:
      - ./data/dev/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"

networks:
  sendy-dev-network:
    driver: bridge
  
