import Head from "next/head";
import { getSession } from "next-auth/client";
import { GetServerSideProps } from "next";
import prisma from "../../utils/db";
import { Project } from "@prisma/client";
import ProjectsTable from '../../components/ProjectsTable'
import Link from 'next/link'

type PropTypes = {
  projects: Project[];
};

export default function ProjectsList({ projects }: PropTypes) {
  return (
    <div>
      <Head>
        <title>sendy 📷 | projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>sendy 📷 | projects</h1>

        <Link href="/projects/new" passHref>
          <button>New Project</button>
        </Link>

        {projects.length === 0 && <p>You have no projects.</p>}
        {projects.length > 0 && <ProjectsTable projects={projects} />}
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });
  if (!session?.user) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  const { email } = session.user;
  const projects = await prisma.project.findMany({
    where: {
      userEmail: email!,
    },
  });
  return {
    props: { projects },
  };
};
