import Head from "next/head";
import { getSession } from "next-auth/client";
import { GetServerSideProps } from "next";
import prisma from "../../utils/db";
import ProjectsTable, {
  PropTypes as ProjectPropTypes,
} from "../../components/ProjectsTable";
import Link from "next/link";

import Image from "next/image";

import {
  Heading,
  Container,
  Button,
  Flex,
  Text,
  Box,
  Spacer,
} from "@chakra-ui/react";
import SendyLogo from "../../assets/sendy.svg";

type PropTypes = ProjectPropTypes & {};

export default function ProjectsList({ projects }: PropTypes) {
  return (
    <div>
      <Head>
        <title>sendy 📷 | projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="960px" pt={12}>
        <Flex alignItems="center" mb={4}>
          <Heading size="xl">sendy</Heading>
          <Image src={SendyLogo} width="72px" height="72px" alt="Sendy logo" />
          <Spacer />
          <Link href="/projects/new" passHref>
            <Button>New Project</Button>
          </Link>
        </Flex>

        <Box mt={4}>
          {projects.length === 0 && <Text>You have no projects.</Text>}
          {projects.length > 0 && <ProjectsTable projects={projects} />}
        </Box>
      </Container>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });
  if (!session?.user) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  const { email } = session.user;
  const projects = await prisma.project.findMany({
    where: {
      userEmail: email!,
    },
    include: {
      _count: {
        select: { submissions: true },
      },
    },
  });
  const props: PropTypes = { projects };
  return { props };
};
