import { Container, Heading } from "@chakra-ui/react";
import axios from "axios";
import { GetServerSideProps } from "next";
import { User } from "next-auth";
import { getSession } from "next-auth/client";
import Head from "next/head";
import { useRouter } from "next/router";
import ProjectForm from "../../components/ProjectForm";
import TopMenu from "../../components/TopMenu";
import { ProjectFormData } from "../../models";

type PropTypes = {
  user: User;
};

export default function NewProject(props: PropTypes) {
  const router = useRouter();
  const onSubmit = async (data: ProjectFormData) => {
    const response = await axios.post("/api/projects", data);
    const { projectId } = response.data;
    localStorage.setItem("created", `project:${projectId}`);
    router.push("/projects");
  };

  return (
    <div>
      <Head>
        <title>Sendy ✈️ | New project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopMenu user={props.user} />
      <Container maxW="960px" p={0}>
        <Heading size="xl" mb={8}>
          New project
        </Heading>
        <ProjectForm onSubmit={onSubmit} />
      </Container>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req });
  if (!session?.user) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  return { props: { user: session.user } };
};
