import { Heading } from '@chakra-ui/react';
import { ClientSafeProvider, getProviders, signIn, getSession } from 'next-auth/client'
import Head from 'next/head'
import Image from 'next/image';

import SendyLogo from '../assets/sendy.svg';

export default function Login({ providers }: {
  providers: Record<string, ClientSafeProvider>
}) {
  return (
    <div>
      <Head>
        <title>sendy 📷 | video sharing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading size="lg">
          sendy
        </Heading>

        <Image src={SendyLogo} width="100px" height="100px" alt="Sendy logo" />

      

        <p>
          Create magic links that let your friends
          record videos into your Google Drive.
        </p>

        <div>
          {Object.values(providers).map(provider => (
            <div key={provider.name}>
              <button onClick={() => signIn(provider.id)}>Sign in with {provider.name}</button>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const session = await getSession(context);
  console.log(session);
  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: '/projects',
      },
    };
  }

  const providers = await getProviders();
  return {
    props: { providers }
  };
}
